ignored:
  - ".git/"
  - ".gitignore"
  - "*.pdf"

license: gpl-3

license-parameters: {
  project-name: "foobar",
  copyright-years: "19XX-20YY"
}

tracked:
  -
    patterns: "*.py"
    prefixes: "#  "
    insert-at: 2
  -
    patterns: [ "*.cpp", "*.h" ]
    prefixes: [ "/* ", " * ", " */" ]
  -
    patterns: "*.txt"
    insert-at: 1
